services:
  web_app:
    build: ./web_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: python3 main.py

  gaze_module:
    build:
      context: ./pupil_docker
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
    devices:
      - /dev/video0:/dev/video0
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: host
    privileged: true
    command: /app/pupil/pupil_src/start.sh