version: '3.8'

services:
  zmq_proxy:
    build:
      context: .
      dockerfile: Dockerfile.ml_cv_python3_8
    volumes:
      - ../app/app_shared_data:/app
    ports:
      - "5559:5559"
      - "5560:5560"
    command: "python3 zmq_proxy.py" # --enable-logging"
    networks:
      - app_network

  web_host:
    build:
      context: .
      dockerfile: Dockerfile.web_host_python3_8
    volumes:
      - ../app/web_host:/app
      - ../app/app_shared_data:/app_shared_data
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/app:/app_shared_data
      - ZMQ_PUB_ADDRESS=tcp://zmq_proxy:5559
      - ZMQ_SUB_ADDRESS=tcp://zmq_proxy:5560
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - zmq_proxy
    command: "python3 main.py" # --enable-logging"

  module_processor:
    build:
      context: .
      dockerfile: Dockerfile.ml_cv_python3_8
    volumes:
      - ../app/module_processor:/app
      - ../app/app_shared_data:/app_shared_data
    devices:
      - "/dev/video0:/dev/video0"  # Webcam
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/app:/app_shared_data
      - ZMQ_PUB_ADDRESS=tcp://zmq_proxy:5559
      - ZMQ_SUB_ADDRESS=tcp://zmq_proxy:5560
    networks:
      - app_network
    depends_on:
      - zmq_proxy
    command: "python3 main.py" #--enable-logging"

  pupil_module:
    build:
      context: .
      dockerfile: Dockerfile.pupil_dev
      args:
          USER_ID: ${UID:-1000}
          GROUP_ID: ${GID:-1000}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - ../app/pupil_module:/pupil_module
      - ../app/app_shared_data:/app_shared_data
      - ../app/pupil_module/pupil_capture_settings:/app/pupil/capture_settings
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - PYTHONPATH=/pupil_module:/app_shared_data
      - XAUTHORITY=/tmp/.docker.xauth
      # Using localhost since Pupil Capture runs on host network
      - ZMQ_PUB_ADDRESS=tcp://localhost:5559
      - ZMQ_SUB_ADDRESS=tcp://localhost:5560
    network_mode: "host"  # Required for Pupil Capture
    group_add:
      - plugdev
      - video
    command: "/pupil_module/start.sh" # debug arg can be added to start.sh


networks:
  app_network:
    driver: bridge