version: '3.8'

services:

  zmq_proxy:
    build:
      context: .
      dockerfile: Dockerfile.ml_cv_python3_8
    volumes:
      - ../app/app_shared_data:/app
    ports:
      - "5559:5559"
      - "5560:5560"
    command: "python3 zmq_proxy.py" # --enable-logging"
    networks:
      - app_network

  web_host:
    build:
      context: .
      dockerfile: Dockerfile.web_host_python3_8
    volumes:
      - ../app/web_host:/app
      - ../app/app_shared_data:/app_shared_data
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/app:/app_shared_data
      - ZMQ_PUB_ADDRESS=tcp://zmq_proxy:5559
      - ZMQ_SUB_ADDRESS=tcp://zmq_proxy:5560
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - zmq_proxy
    command: "python3 main.py" # --enable-logging"

  module_processor:
    build:
      context: .
      dockerfile: Dockerfile.ml_cv_python3_8
    volumes:
      - ../app/module_processor:/app
      - ../app/app_shared_data:/app_shared_data
    devices:
      - "/dev/video0:/dev/video0"  # Webcam
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/app:/app_shared_data
      - ZMQ_PUB_ADDRESS=tcp://zmq_proxy:5559
      - ZMQ_SUB_ADDRESS=tcp://zmq_proxy:5560
    networks:
      - app_network
    depends_on:
      - zmq_proxy
    command: "python3 main.py --enable-logging"

networks:
  app_network:
    driver: bridge