# Use the official ROS Noetic image as the base
FROM osrf/ros:noetic-desktop-full

# Install RViz and necessary packages for software rendering and debugging
RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    bash-completion \
    ros-${ROS_DISTRO}-image-transport-plugins \
    ros-${ROS_DISTRO}-teleop-twist-keyboard \
    ros-${ROS_DISTRO}-husky-* \
    python3-wstool \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-dev \
    python3-pip \
    libgl1-mesa-dri \
    libglvnd0 \
    libgl1 \
    libglx0 \
    libegl1 \
    libxext6 \
    libx11-6 \
    bash-completion \
    iputils-ping \
    net-tools \
    iproute2 \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Set up environment variables
ENV ROS_DISTRO noetic
ENV LIBGL_ALWAYS_SOFTWARE 1
ENV DISPLAY=:0

# Create catkin workspace and package directories
RUN mkdir -p /root/catkin_ws/src/ugv_mission_pkg/srv && \
    mkdir -p /root/catkin_ws/src/ugv_mission_pkg/msg
WORKDIR /root/catkin_ws/src/ugv_mission_pkg

# Copy service files
COPY ../app/mission_manager/srv/* ./srv/

# Copy the msg
COPY ../app/mission_manager/msg/* ./msg/

COPY ../app/mission_manager/package.xml ./
COPY ../app/mission_manager/CMakeLists.txt ./

# Create message files
WORKDIR /root/catkin_ws/src/ugv_mission_pkg

# Build the workspace
WORKDIR /root/catkin_ws
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"

WORKDIR /root
COPY .docker/pip_requirements/ros_noetic_remote_master.txt /root/req.txt
RUN pip3 install -r /root/req.txt

# Create a script to update /etc/hosts and source ROS workspace
RUN echo '#!/bin/bash\n\
if [ ! -z "$ROBOT_IP" ]; then\n\
  echo "$ROBOT_IP $ROBOT_HOSTNAME" >> /etc/hosts\n\
fi\n\
source /root/catkin_ws/devel/setup.bash\n\
exec "$@"' > /update-hosts.sh && chmod +x /update-hosts.sh

# Set the script as the entry point
ENTRYPOINT ["/update-hosts.sh"]