# Dockerfile.visualizer
FROM python:3.8-slim-buster

# Install system dependencies including graphviz
RUN apt-get update && apt-get install -y \
    graphviz \
    graphviz-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python dependencies
COPY .docker/pip_requirements/visualizer.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt