FROM python:3.9-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY pip_requirements/web_host_python3_9.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
